### ISSUE TITLE
abréviations de fonction auteur à clarifier

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#1]
clarifier et détailler les abréviations de fonction

préfacier = préf. = `Extra` >`editorial-director`
traducteur = trad. = `Traducteur`
éditeur scientifique = éd. = `Editeur` - pour l'instant abréger en dir. dans fichier csl

**Comment by fflamerie** [comment]
clarifier et détailler les abréviations de fonction

préfacier = préf. = Extra >editorial-director
traducteur = trad. = Traducteur
éditeur scientifique = éd. = Editeur - pour l'instant abréger en éd. dans fichier csl

**Comment by fflamerie** [comment]
préfacier = préf. = Extra >editorial-director
traducteur = trad. = Traducteur
éditeur scientifique = dir. = Editeur - pour l'instant abréger en dir. dans fichier csl

Corriger les modèles dans le guide

**Comment by fflamerie** [comment]
préfacier = préf. = Extra >editorial-director
traducteur = trad. = Traducteur
**éditeur scientifique colloques et ouvrages = dir.**
**éditeur scientifique chapitres de livre = éd.**

**Comment by PGravier** [comment]
Pour toutes les modifications du guide, je m'y attelle cette semaine.

**Comment by fflamerie** [comment]
Dans le guide, afin de clarifier et simplifier, pourrait-on indiquer directement dans les modèles pour les colloques (dir.) au lieu de (fonct.)? (dir.) est en effet la seule fonct. applicable.

**Comment by PGravier** [comment]
C'est reporté.
