### ISSUE TITLE
locator = obligatoire en note de bas de page

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#10]
Mentionne-t-on systématiquement la référence à une page ou un paragraphe précis en note de bas de page?
**Paramétrage effectué = si mention de `locator `en note de bas de page, on l'affiche et on n'affiche pas de pagination ou de nombre total de page ; si pas de `locator` en note de page, on n'affiche rien, on n'affiche pas de pagination ou de nombre total de pages.**

**Comment by PGravier** [comment]
OK avec votre proposition. Les pages concernées sont toujours à mentionner en notes de bas de page, et jamais le nb total de pages du document, réservé à la bibliographie.

**Comment by fflamerie** [comment]
OK ajout d'une note globale CSL au début du guide
