### ISSUE TITLE
article de revue en ligne : modèle à réviser - URL pas affichable si pagination

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#13]
https://forums.zotero.org/discussion/comment/273572/#Comment_273572
 adamsmith
April 5, 2017
The other thing (and this isn't new) is that Zotero treats an article as not having a URL if it has a page range (as this one does). The style tests for the presence of a URL before adding the access date.

**Comment by fflamerie** [comment]
Je propose le modèle suivant ; il s'agit à la fois d'assurer la compatibilité avec Zotero, et d'indiquer la mention [en ligne] de façon plus cohérente avec les modèles des autres types de document.
NB déplacer la mention [en ligne] permet aussi de résoudre la difficulté liée au fait qu'il n'y a pas de champ "partie" et que l'on doit saisir cette information dans le même champ que le titre de la revue.
_On mentionne l'URL dans la notice Zotero, car c'est une condition pour l'affichage de la mention [en ligne] et de la date de consultation, mais on ne l'affiche jamais._

* Modèle bibliographie

Auteur \[NOM prénom\], « Titre de l’article, complément du titre » \[en ligne\], _Titre de la revue_, partie, mois année, numéro, pagination globale, \[consulté le …\].

* Modèle note de bas de page

Auteur \[NOM prénom\], « Titre de l’article » \[en ligne\], _Titre de la revue abrégé_, partie, année, numéro de paragraphe ou des pages concernées, \[consulté le …\].

**Comment by PGravier** [comment]
C'est entendu. Il faudra néanmoins indiquer aux utilisateurs d'ajouter l'URL simplifiée manuellement. C'est une indication d'accès indispensable, not. quand la revue est publiée hors ressources numériques habituelles (sites d'organisations internationales, sites d'associations de recherches, sites d'associations, etc.).

**Comment by fflamerie** [comment]
Je ne l'avais pas vu avant, mais il faudra aussi que la mention de partie soit en italiques, puisqu'elle sera intégrée au titre de la revue. C'est corrigé dans le guide.
Comme indiqué ci-dessus s'il y a une pagination Zotero considère qu'il n'y a pas d'URL, pas de date de consultation, etc.
La solution suivante permettrait d'afficher la mention en ligne et l'URL, mais pas la date de consultation, qui devrait être gérée manuellement, ce qui me semble excessivement contraignant et inutile.
* Renseigner dans le champ `URL` de la notice Zotero l'URL spécifique d'accès directe à l'article si applicable, ou l'URL simplifiée : cela permet d'y accéder directement et facilement depuis la bibliothèque Zotero 
* Renseigner dans le champ `Loc. dans l'archive` de la notice Zotero l'URL simplifiée qui sera affichée dans la bibliographie
Le style affiche donc bien [en ligne] + URL ; si suppression date de consultation OK, je corrigerai le pb de ponctuation après la pagination en bibliographie

**Comment by fflamerie** [comment]
ajouter date de consultation dans champ ad hoc type catalogue de bibliothèque, etc.

**Comment by fflamerie** [comment]
Revu proprement grâce à l'option "Inclure les URL..." du gestionnaire de style - plus de recours à des champs ad hoc
