### ISSUE TITLE
courriel : distinguer courriel et message sur un forum?

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#17]
Zotero et CSL permettent de distinguer les 2 types : est-il utile et pertinent de répercuter cette distinction dans le code? Cela n'apporterait pas un gain considérable en termes de temps de saisie, mais permettrait un code plus propre (le titre du forum serait indiqué dans le champ adéquat et non dans le champ URL).

**Comment by fflamerie** [comment]
Il serait souhaitable de distinguer ces 2 types de document, car ils sont malgré tout différents. Le courriel n'est finalement qu'une lettre électronique: une information comme la date de consultation n'est pas forcément pertinente et contraint à une saisie lourde dans Zotero. Le message sur un forum se rapproche davantage de la page web, avec la nécessité/pertinence d'indiquer une URL et une date de consultation (ces 2 éléments sont prévus dans la notice Zotero de message sur un forum). Aussi je soumets les propositions de modèle ci-dessous. Si elles conviennent, je mets à jour le guide et le style en conséquence ; pour le style j'ai ajouté le type `post ` (=message sur un forum) mais je n'ai pas modifié le type `personal_communication` (=courriel)

**Courriel** 
= modèle actuel note de bas de page, il serait appliqué aussi pour la bibliographie
Auteur \[NOM Prénom\], _Sujet du courriel_ \[courriel\], date de l’envoi \[JJ mois AAAA\]

**Message sur un forum**
= compromis page web/courriel

* Bibliographie
Auteur \[NOM Prénom\], "Sujet du courriel" \[courriel\], sur \[_nom de la liste de diffusion ou du forum_\], date de l’envoi \[JJ mois AAAA\], \[consulté le...\] sur \[URL de la liste de diffusion ou du forum\].

* Note de bas de page
Auteur \[NOM Prénom\], "Sujet du courriel" \[courriel\], sur \[_nom de la liste de diffusion ou du forum_\], date de l’envoi \[JJ mois AAAA\], \[consulté le...\].

**Comment by fflamerie** [comment]
Proposition implémentée dans guide et style

**Comment by PGravier** [comment]
J'ai reporté la proposition en refaisant la p. 29 du guide.

**Comment by fflamerie** [comment]
Je pense que 2 sections distinctes seraient préférables.
