### ISSUE TITLE
norme juridique : ponctuation pays, auteur

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#18]
Les exemples ne suivent pas la syntaxe du modèle:
modèle = PAYS, AUTEUR
exemple = FRANCE. MINISTERE...
Quel est le bon délimiteur du : `.` ou `,` ?

**Comment by PGravier** [comment]
C'est une divergence non résolue, qui a subsisté dans le modèle.
Nous allons retenir la virgule, qui avait la faveur du groupe pour l'ensemble des questions.

**Comment by fflamerie** [comment]
Dans la version précédente du guide, la mention de PAYS était réservée à la bibliographie. Dans la nouvelle version elle apparaît aussi en note de bas de page. Qu'en est-il?

**Comment by PGravier** [comment]
Ce n'est pas tout à fait cela : la nouvelle version indique plus correctement, en bibliographie et en notes de base de pages, que le pays peut être indiqué ou non (conformément au NB qui indique qu'il peut être utile s'il y a ambiguïté seulement).

**Comment by fflamerie** [comment]
Donc si le pays est indiqué en bibliographie il l'est aussi en note de bas de page?
Cela simplifierait le code :+1:
