### ISSUE TITLE
cas particulier auteur: afficher un 4è auteur avant et al.

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#20]
Guide:
>Un auteur, dont l’omission nuirait à la bonne compréhension de la référence ou de son choix, peut exceptionnellement être placé en quatrième position avant la mention « _et al._ ».

Possible uniquement pour les notes de bas de page et uniquement pour désambiguïser - voir <http://docs.citationstyles.org/en/stable/specification.html#disambiguation> - attribut `disambiguate-add-names` paramétré, mais vérifier s'il fonctionne pour les styles de type `note`

**Comment by PGravier** [comment]
Il s'agit de toute façon d'une rectification de politesse : cela devrait aller si c'est possible au niveau des bas de page.

**Comment by fflamerie** [comment]
Ce n'est possible ni au niveau des notes de bas de page, ni dans la bibliographie. L'attribut mentionné _supra_ sert à désambiguïser les appels de citation automatiquement dans un modèle auteur-date.
Dans le modèle note, il n'y a pas d'ambiguïté à lever, puisque la note de bas de page comporte d'autres éléments qu'auteur+date. J'ai ajouté une note dans le guide.
