### ISSUE TITLE
cas particulier publications: [s. n.] etc. pour quel type de document?

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#22]
Clarifier pour quels types de document les mentions doivent être générées : 
* [s. l.] = livres, chapitres et articles de colloques
* [s. d.] = livres, chapitres, articles de colloque et thèses - autres types de document ?
* [s. n.] = livres, chapitres, articles de colloque et thèses

**Comment by PGravier** [comment]
OK pour vos propositions, cependant je retirerais s.d. pour les thèses : j'ai l'impression que la date est toujours disponible, comme le lieu. De même, je retirerais s.n. pour les thèses, puisqu'elles n'ont pas d'éditeur pour leur version non-commerciale (non-livre). Ces mentions sont par ailleurs en voie de suppression des notices de thèses depuis 2016.

**Comment by fflamerie** [comment]
OK alors on a qqchose de très uniforme :+1: 

- [s. l.] = livres, chapitres et articles de colloques
- [s. d.] = livres, chapitres, articles de colloque
- [s. n.] = livres, chapitres, articles de colloque

C'est paramétré en partie dans le style et précisé dans le guide.
Dans le style, [s. d.] s'affiche en bibliographie aussi pour les articles de revue et les thèses. Si on peut s'en accommoder, cela économise beaucoup de code.
