### ISSUE TITLE
termes latins de renvoi : loco citato pas possible

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#25]
Zotero ne distingue pas les références:
* identiques, contiguës, sans mention de `locator` = _Ibidem_ dans le guide
* identiques, contiguës, avec mention du même `locator` = _Loco citato_ dans le guide

Ces 2 cas correspondent au même paramétrage dans Zotero, _i. e._ `ibid`
Voir : <https://github.com/fflamerie/zotero_csl_2018/blob/master/2018_csl_cours.md#ibid-op-cit-etc>

**Comment by PGravier** [comment]
loc. cit. n'étant qu'une modalité particulière de ibid., ce n'est pas une difficulté. Il faudra garder la mention de loc. cit. dans le guide, même si elle n'est pas employée dans le style, car les abréviations latines étaient la demande principale des doctorants en formation.

**Comment by fflamerie** [comment]
J'ai ajouté une note à ce sujet dans le guide.
