### ISSUE TITLE
guide : préciser modèles de saisie date de consultation

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#27]
Dans le guide, les modèles n'indiquent qu'imparfaitement la manière de saisir la date de consultation. Il s'agirait de l'expliciter, en remplaçant dans tous les modèles: 

[consulté le ...] 

par

[consulté le JJ mois AAAA]

**Comment by PGravier** [comment]
C'est entendu, je le reporte.
