### ISSUE TITLE
ponctuation : séparateur de références dans une note

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#29]
Quel caracactère faut-il utiliser pour séparer des citations multiples lorsque l'on insère plusieurs références dans une même note?
Ou une note = une référence? Auquel cas il pourrait être utile de le mentionner explicitement

**Comment by PGravier** [comment]
Les avis convergeant nécessitent souvent des références multiples. Retenir le point-virgule comme séparateur des références.

**Comment by fflamerie** [comment]
Modifié dans le style + ajout d'une recommandation particulière dans le guide.
Esprit d'escalier... Y a-t-il des consignes concernant l'ordre des références à appliquer (par exemple par date, par nom d'auteur, etc.) pour les références multiples en note de bas de page? Les critères de tri peuvent être paramétrés dans le style CSL pour qu'ils puissent être effectués automatiquement. Si oui, on crée une nouvelle issue, si non on l'explicite dans le guide.

**Comment by PGravier** [comment]
Je n'ai jamais vu de critère de tri, c'est souvent par ordre d'importance plutôt, donc selon analyse du rédacteur.

**Comment by fflamerie** [comment]
Le délimiteur retenu est finalement l'espace, pour ne pas introduire de ponctuation superflue lorsque la note comporte à la fois du texte et des citations.
