### ISSUE TITLE
ponctuation : gestion du point final pbtique

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#30]
Au prix de quelques contorsions, le style applique bien la consigne de ne pas afficher de` . `après une URL en bibliographie. Mais du coup il n'y a pas de point final non plus pour les documents sans pagination ni nombre de pages, _i. e._ : les thèses microfichées, les brevets, les entretiens oraux.
Serait-il envisageable, lorsqu'il y a une URL, qu'elle soit précédée d'un point et non d'une virgule? Cela règlerait les problèmes mentionnés précédemment et rendrait aussi plus cohérent le style.
A la place de:

AUTEUR, « Titre de l’article ou de la page », sur _Titre de la page d'accueil_ \[en ligne\], publié le …, \[consulté le…\], URL

MAÎTRE ÉOLAS, « Pour en finir avec la séparation des pouvoirs », sur _Journal d’un avocat : Instantanés de la justice et du droit_ \[en ligne\], publié le 21 février 2017, \[consulté le 21 mars 2017\], http://www.maitre-eolas.fr](http://www.maitre-eolas.fr

on aurait:

AUTEUR, « Titre de l’article ou de la page », sur _Titre de la page d'accueil_ \[en ligne\], publié le …, \[consulté le…\]. URL

MAÎTRE ÉOLAS, « Pour en finir avec la séparation des pouvoirs », sur _Journal d’un avocat : Instantanés de la justice et du droit_ \[en ligne\], publié le 21 février 2017, \[consulté le 21 mars 2017\]. http://www.maitre-eolas.fr](http://www.maitre-eolas.fr

**Comment by PGravier** [comment]
Aucun problème pour que les URL soient précédées d'un point. Je l'ajoute aux modifications du style à effectuer sans la semaine qui vient (je confirmerai au fur et à mesure pour le sujets qui restent ouverts).

**Comment by fflamerie** [comment]
Modifié style et guide.
