### ISSUE TITLE
Revue avec parties

### ISSUE THREAD

**Issue by PGravier** [fflamerie/csl_ed_droit_ubx#31]
Comme demandé, ajout d'un exemple de revue **avec partie** : "La cour de cassation s'est prononcée contre la requalification des contrats d’assurance-vie en contrats de capitalisation"
Les parties concernent plusieurs revues (JCP G, Bull. civ. ...). En général, la référence est indiquée sur le modèle : année, partie, numérotation interne à la partie, pages (2005, I, 111, p. 253-285).

**Comment by fflamerie** [comment]
Le guide indique l'ordre Titre de la revue, **partie, mois année**, etc. 
Faut-il modifier le guide comme suit ? : Titre de la revue, **mois année, partie**, etc. 
En note et bibliographie?

**Comment by PGravier** [comment]
Il serait lourd de faire une section spéciale pour les revues à parties, je modifie le style comme proposé, en note et bibliographie.

**Comment by fflamerie** [comment]
En lisant le guide, je déduis que l'on supprime la mention de partie des notes de bas de page : est-ce bien le cas?
Pour l'instant en note de bas de page on a:
Auteur \[NOM prénom\], « Titre de l’article », _Titre de la revue abrégé_, partie, année, numéro de paragraphe ou des pages concernées.

**Comment by PGravier** [comment]
Non, c'est un oubli dans les modifications : la partie est tjs mentionnée dans les notes de bas de pages. J'ai corrigé dans le guide Word.
J'en profite pour ajouter : nous sommes bien d'accord que [en ligne] suit le titre de l'article et non la revue ? Ce n'était pas rigoureux dans les exemples donnés, que j'ai modifiés en ce sens.
