### ISSUE TITLE
ouvrages numériques URL complètes/incomplètes

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#32]
Afin d'uniformiser et de simplifier, serait-il possible de généraliser la consigne d'usage des URL simplifiées aux ouvrages? Dans la version Word du guide, si les libellés sont soit l'URL simplifiée soit la mention en ligne, les liens hypertexte sont les liens d'accès précis.
Cela contraindrait à renseigner 2 champs différents dans les notices Zotero, et à ajouter manuellement les liens aux mentions [en ligne].

**Comment by PGravier** [comment]
J'hésite beaucoup.
Autant pour les revues dans les BDD (Dalloz, Lexis...), l'URL précise n'a pas grand sens, autant pour les rapports officiels, etc. cela permet d'indiquer dans quelle section du site trouver l'information voire de bénéficier d'une URL pérenne.

**Comment by fflamerie** [comment]
Autre proposition pour simplifier  davantage : dans les spécifications Zotero on ne mentionne plus cette notion d'URL simplifiée, on la réserve au guide imprimé et aux non-utilisateurs de Zotero, pour lesquels il peut être plus simple de mentionner une URL simplifiée. On met à jour en conséquence les exemples de la bibliothèque Zotero avec les URL réelles et précises.

**Comment by fflamerie** [comment]
Dans les spécifications Zotero on utilise uniquement les URL "réelles", on ne tiens pas compte de la notion d'URL simplifiée.
