### ISSUE TITLE
Cas des titres abrégés de mélanges

### ISSUE THREAD

**Issue by PGravier** [fflamerie/csl_ed_droit_ubx#34]
Comment faire figurer un titre abrégé pour des mélanges?

**Comment by fflamerie** [comment]
Cite-t-on seulement un chapitre de mélanges ou peut-on citer aussi le volume de mélanges globalement?
Le cas numéro 2 correspond à celui des livres et il faut seulement ajouter un exemple dans la bibliothèque Zotero + une note dans le guide.
Le cas numéro 1 correspond à un exemple existant dans la bibliohtèque (ici : https://www.zotero.org/groups/2190104/items/N8ZRTXUF), il est traité en chapitre de livre. On ne peut pas utiliser le champ `Titre abrégé` car il s'agit du titre abrégé du document, i. e. du titre abrégé du chapitre si applicable. Je crains qu'il ne faille détourner un champ Zotero non prévu pour cela. A ce moment-là on pourrait utiliser le champ `Archive`.

**Comment by PGravier** [comment]
On ne cite normalement que l'article (cas 1), et c'est toute l'utilité du titre abrégé. Pas de pb pour l'utilisation du champ archive, en tout cas je ne peux pas voir de contre-indication.

**Comment by fflamerie** [comment]
Fait - le titre abrégé du recueil de mélanges doit être saisi dans le champ cote
