### ISSUE TITLE
ajouter modèle "article de colloque" vidéo en ligne

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#37]
* utiliser le type "article de colloque" pour avoir les bons champs de colloque (intitulé, lieu, etc.)
* voir quel champ utiliser pour spécifier la mention [vidéo]

**Comment by fflamerie** [comment]
utiliser plutôt le type de document "Présentation" ; le champ "Type" permettrait de spécifier "Enregistrement vidéo" ou autre, ce qui permettrait d'utiliser plus largement ce type de document pour toutes les conférences orales, filmées ou non
![capture d ecran 2018-09-15 a 12 45 40](https://user-images.githubusercontent.com/33718229/45585502-b0523800-b8e5-11e8-8e93-2ac9e3f93e27.png)

**Comment by fflamerie** [comment]
## Citer une présentation 

Type de présentation = contenu du camp Zotero `Type`, il resterait à définir des exemples de valeurs possibles, telles que "communication", "poster", "conférence" ou tout autre terme qui vous semblerait pertinent.

### Modèles pour la bibliographie

Auteur \[NOM prénom\], Titre de la présentation \[type de présentation\], présenté à _Titre du colloque ou de la réunion_, lieu, JJ mois AAAA.

### Modèles pour les notes de bas de page

Auteur \[NOM prénom\], Titre de la présentation \[type de présentation\], présenté à _Titre du colloque ou de la réunion_, lieu, JJ mois AAAA.

## Citer une présentation disponible sur internet

Pour les conférences disponibles en vidéo sur internet je verrais 2 possiblités:
* préciser "en ligne" dans le `Type`, par exemple "conférence en ligne" (cela fait un peu bizarre, on dirait qu'il s'agit d'une visioconférence),
* distinguer les mentions de type et de "en ligne", on aurait ainsi \[type de présentation\]\[en ligne\]

### Modèles pour la bibliographie

Auteur \[NOM prénom\], Titre de la présentation \[type de présentation\], présenté à _Titre du colloque ou de la réunion_, lieu, JJ mois AAAA, \[consulté le JJ mois AAAA\]. URL

### Modèles pour les notes de bas de page
Auteur \[NOM prénom\], Titre de la présentation \[type de présentation\], présenté à _Titre du colloque ou de la réunion_, lieu, JJ mois AAAA, \[consulté le JJ mois AAAA\].

**Comment by PGravier** [comment]
Je crains que nous ne nous engagions trop loin, surtout sans le groupe de travail. Je vous propose :


**Citer une contribution parmi les actes non-publiés d’un colloque, diffusé sur Internet**

**Modèle pour la bibliographie**
Auteur [NOM prénom], Titre de la contribution, in _Titre du colloque_ [non publié], lieu du colloque, date du colloque [consulté le jj mois AAAA]. URL éventuelle

**Modèle pour les notes de bas de page**
Auteur [NOM prénom], Titre de la contribution, in _Titre du colloque_ [non publié], lieu du colloque, date du colloque [consulté le jj mois AAAA].


Exemples pour la bibliographie
ARENS Chantal, Propos introductifs, in Droit souple, textes préparatoires, ... : pour quelle efficacité du droit de la concurrence ? [non publié], Cour d'appel de Paris, 20 octobre 2017, [consulté le 26 septembre 2018]. https://www.youtube.com/watch?v=s8PkCOhW2fM&list=PL5VN7j-dxidRD4exfMm11njkurgNM7DSl

Exemples pour les notes de bas de page
ARENS Chantal, Propos introductifs, in Droit souple, textes préparatoires, ... : pour quelle efficacité du droit de la concurrence ? [non publié], Cour d'appel de Paris, 20 octobre 2017, [consulté le 26 septembre 2018].

**Comment by fflamerie** [comment]
A implémenter dans une version ultérieure du style
