### ISSUE TITLE
ajouter un exemple de livre avec un traducteur ou un éditeur, pour montrer la différence de saisie avec le préfacier

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#5]

**Comment by PGravier** [comment]
Fait dans la bibliothèque du groupe Zotero (livre+traducteur) : Théorie pure du droit ; suivie de L'influence de Kelsen sur les théories du droit dans l'Europe francophone

**Comment by fflamerie** [comment]
OK merci, j'ai mis à jour votre exemple et ajouté le lien dans le Guide
