### ISSUE TITLE
tomaison : exemple avec nombre de volumes à fournir

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#6]
Ajouter un exemple d'un livre avec une mention de `Nb de volumes`. Ou n'est-ce pas applicable? En fonction du modèle on corrigera le code pour afficher correctement l'espace entre `vol.` et le numéro de vol.

**Comment by PGravier** [comment]
Fait, ajout à la bibliothèque du groupe Zotero (livre en 3 tomes) : Traité de droit constitutionnel

**Comment by fflamerie** [comment]
Plus précisément, il s'agit du cas où le livre considéré est l'un des tomes d'un ouvrage en plusieurs tomes. J'ai adapté votre exemple en ce sens. Ce cas n'est pas prévu dans les consignes.
Pour l'instant l'affichage est le suivant: `vol. 3/1`, où 3 = le nbre total de volumes et 1 = numéro du volume

**Comment by fflamerie** [comment]
On n'affiche pas le nombre total de volumes, modifier CSL pour supprimer affichage de cette mention

**Comment by fflamerie** [comment]
Ajouter un exemple : tome d'un livre en plusieurs tomes, chacun des tomes ayant des titres propres différents @PGravier

**Comment by PGravier** [comment]
Exemple inadapté supprimé, et ajout de l'exemple : Traité de droit constitutionnel. Tome deuxième, La théorie générale de l'État (2e vol. sur 3 avec titres propres).

**Comment by PGravier** [comment]
Il faudra peut-être voir ce sujet ensemble : je ne vois pas le titre abrégé dans l'exemple.

**Comment by fflamerie** [comment]
Moi oui ; à revoir ensemble en effet.
![titre_abrege](https://user-images.githubusercontent.com/33718229/45345124-aeb30800-b5a5-11e8-85e8-9f2a8383428d.png)
