### ISSUE TITLE
mention d'édition ouvrage/chapitre

### ISSUE THREAD

**Issue by fflamerie** [fflamerie/csl_ed_droit_ubx#9]
La mention d'édition n'est pas affichée en note de bas de page pour les livres, en revanche elle l'est pour les chapitres : est-il cohérent de l'afficher pour les chapitres de livre ?
**Paramétrage effectué = pas affichée**

**Comment by PGravier** [comment]
Encore une coquille dans la conception du modèle : la mention de l'édition en note de bas de page sera retirée du modèle pour les chapitres de livres / contributions à ouvrage collectif. OK donc pour la retirer.

**Comment by fflamerie** [comment]
Modifié et commenté dans le guide
